// Fill out your copyright notice in the Description page of Project Settings.

#pragma once

#include "NativeGameplayTags.h"

namespace HeroGameplayTags
{
	/** Input Tags **/
	MMORPG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Move);
	MMORPG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Look);
	MMORPG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_EquipAxe);
	MMORPG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_UnequipAxe);
	MMORPG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_EquipSword);
	MMORPG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_UnequipSword);
	MMORPG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_LightAttack_Axe);
	MMORPG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_HeavyAttack_Axe);
	MMORPG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_LightAttack_FrostKnight);
	MMORPG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_HeavyAttack_FrostKnight);

	/** Warrior Player Tags **/
	MMORPG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Warrior_Ability_Equip_Axe);
	MMORPG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Warrior_Ability_Unequip_Axe);
	MMORPG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Warrior_Ability_Attack_Light_Axe);
	MMORPG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Warrior_Ability_Attack_Heavy_Axe);

	MMORPG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Warrior_Ability_HitPause);

	MMORPG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Warrior_Weapon_Axe);

	MMORPG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Warrior_Event_Equip_Axe);
	MMORPG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Warrior_Event_Unequip_Axe);

	MMORPG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Warrior_Event_HitPause);

	MMORPG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Warrior_SetByCaller_AttackType_Light);
	MMORPG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Warrior_SetByCaller_AttackType_Heavy);

	/** Frost Knight Tags **/
	MMORPG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(FrostKnight_Ability_Attack_Light);
	MMORPG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(FrostKnight_Ability_Attack_Heavy);

	MMORPG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(FrostKnight_Ability_Equip_Sword);
	MMORPG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(FrostKnight_Ability_Unequip_Sword);

	MMORPG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(FrostKnight_Ability_HitPause);

	MMORPG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(FrostKnight_Weapon_Sword);

	MMORPG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(FrostKnight_Event_Equip_Sword);
	MMORPG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(FrostKnight_Event_Unequip_Sword);
	MMORPG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(FrostKnight_Event_Scale_Sword);

	MMORPG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(FrostKnight_Event_HitPause);


	/** Enemy Tags **/
	MMORPG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_Ability_Melee);
	MMORPG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_Ability_Ranged);
	MMORPG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_Weapon);

	/** Shared tags **/
	MMORPG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Status_JumpToFinisher);
	MMORPG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Ability_HitReact);
	MMORPG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Ability_Death);

	MMORPG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Event_HitReact);
	MMORPG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Event_MeleeHit);

	MMORPG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_SetByCaller_BaseDamage);
	MMORPG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Status_Dead);
}
